#!/bin/sh

# Create a temporary directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORK_DIR="$( mktemp -d -p "$DIR" )"

if [[ ! "$WORK_DIR" || ! -d "$WORK_DIR" ]]; then
	echo "Could not create a working directory"
	exit 1
fi

function cleanup {
	# rm -rf "$WORK_DIR"
	echo "Done."
}

trap cleanup EXIT

# Download tools
cd $WORK_DIR
echo $(pwd)
